[phases.setup]
nixPkgs = ["php82", "php82Extensions.mysqli", "php82Extensions.curl", "php82Extensions.fileinfo", "php82Extensions.exif", "php82Extensions.mbstring", "php82Extensions.gd", "composer"]

[phases.install]
cmds = ["composer install --no-dev --optimize-autoloader"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t . router.php"
